# Generated by Django 3.2.9 on 2021-11-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=30)),
                ('res_adrs', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=20)),
                ('subcategory', models.CharField(default='', max_length=40)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=10)),
                ('images', models.ImageField(default='', upload_to='foodie/images')),
            ],
        ),
    ]
