# Generated by Django 3.2.9 on 2021-12-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=90)),
                ('phone', models.IntegerField(max_length=13)),
                ('email', models.EmailField(max_length=90)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField(max_length=10)),
            ],
        ),
    ]
